CREATE DATABASE `ua_surveillance` /*!40100 COLLATE 'latin1_swedish_ci' */;

CREATE USER 'UA-user'@'%' IDENTIFIED BY 'ua-user';
GRANT SELECT, LOCK TABLES, ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE VIEW, DELETE, DROP, INSERT, UPDATE, TRIGGER, REFERENCES  ON *.* TO 'UA-user'@'%';
FLUSH PRIVILEGES;